In [11]:
# Задача 1
import numpy as np

n = int(input()) # размер Numpy вектора
x = int(input()) # координата элемента вектора, который должен быть равен 1. Остальные должны быть равны 0
# 0 <= x < n

a = np.zeros(n)

a[x] = 1

print(a)

10
5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [16]:
# Задача 2
import numpy as np

# Создайте Numpy вектор, состоящий из чисел от n до m с шагом s

n = int(input()) 
m = int(input())
s = int(input())

a = np.arange(n, m, s)

print(a)

1
10
2
[1 3 5 7 9]


In [22]:
# Задача 3
import numpy as np

# Создайте матрицу 3х3 со значениями от 0 до 8. Значения нужно сгенерировать

a = np.arange(0, 9).reshape(3, 3)

print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
# Задача 4
import numpy as np

# Создайте матрицу 4х4 со случайными значениями
#Найдите максимальное значение первой строки, минимальное - второй, среднее - третьей, сумму - четвертой

a = np.random.normal(size = 16).reshape(4, 4)

maxx = max(a[0])
minx = min(a[1])
sr = (a[2][0] + a[2][1] + a[2][2] + a[2][3]) / 4
summ = a[3][0] + a[3][1] + a[3][2] + a[3][3]

print(a)
print()
print("Максимальное в первой:", maxx)
print("Минимальное во второй:", minx)
print("Среднее в третьей:", sr)
print("Сумма в четвертой:", summ)

[[-1.07734197  1.36909538 -0.33909084 -1.41921066]
 [ 0.23972836 -1.33461276 -1.10283651 -0.50402716]
 [-0.71510125  1.08994543 -0.72406336  0.48173952]
 [ 1.59403071 -0.25769097 -0.26082558  1.03322369]]

Максимальное в первой: 1.3690953843936424
Минимальное во второй: -1.334612759684321
Среднее в третьей: 0.033130086834929504
Сумма в четвертой: 2.1087378560630925


In [31]:
# Задача 5
import numpy as np

# Создайте диагональную матрицу 5х5, все ненулевые элементы равны 5

a = np.zeros(25).reshape(5, 5)

for i in range(0, 5):
    a[i][i] = 5

diagonal = np.diag(a)

print(a)
print()
print(diagonal)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]

[5. 5. 5. 5. 5.]


In [57]:
# Задача 6
import numpy as np

# Создайте Numpy массив случайных чисел размерности 6х6х6 и найдите максимальное значение среди всех элементов

a = np.random.normal(size = 216).reshape(6, 6, 6)

a_simple = a.flatten() # a.ravel ???
maxx = max(a_simple)

print(maxx)
print()
#print(a)

2.1908103856748333



In [126]:
# Задача 7
import numpy as np

# Напишите функцию, которая принимает на вход 2 Numpy матрицы, проверяет, можно ли их перемножить, 
# и если можно - то перемножает и возвращает транспонированную результирующую матрицу
l = [2, 3]

x = np.random.choice(l)
y = np.random.choice(l)
a = np.random.randint(0, 10, size = (x * y)).reshape(y, x) # матрица А
print(a)
print()

z = np.random.choice(l)
w = np.random.choice(l)
b = np.random.randint(0, 10, size = (z * w)).reshape(w, z) # матрица Б
print(b)
print()

# длина первой = высоте второй ПЕРЕМНОЖАЕМ !
if x == w:
    k = a @ b
    print(k.T)

[[9 3]
 [6 2]
 [6 5]]

[[2 2]
 [3 2]]

[[27 24]
 [18 16]
 [27 22]]

[[27 18 27]
 [24 16 22]]


In [6]:
# Задача 8
import numpy as np

# Дана функция f(x1, x2) = x1**2 + 2*x2**2 + e**(x1+x2)
# Найдите минимум данной функции, завершив вычисления при погрешности e = 0.5,
# выбрав в качестве начального приблежения точку (0, 0) и коэффициент шага H = 0.1

def func(x, y):
    return x*x + 2.0 * y*y + np.exp(x + y)

def f_x(func, x, y, eps=0.001):
    return (func(x+eps, y) - func(x, y)) / eps

def f_y(func, x, y, eps=0.001):
    return (func(x, y+eps) - func(x, y)) / eps

EPS = 0.001
INIT = np.array([1.0, -1.75])
LEARN_RATE = 0.05
ITER = 10000

X_prev = INIT
delta = 1
for i in range(ITER):
    if delta > EPS:
        fxx = f_x(func, X_prev[0], X_prev[1], eps=0.001)
        fyy = f_y(func, X_prev[0], X_prev[1], eps=0.001)
        grad = np.array([fxx, fyy])

        X_next = X_prev - LEARN_RATE * grad    

        delta = np.sqrt(np.sum(grad*grad))
        
        X_prev = X_next
        
    else:
        break

print(f"Значение функции {func(X_next[0], X_next[1]).round(4)}")
print(f"x_min {X_next[0].round(4)}")
print(f"y_min {X_next[1].round(4)}")
print(f"Производная в x_min {f_x(func, X_next[0], X_next[1], eps=0.001).round(4)}")
print(f"Производная в y_min {f_y(func, X_next[0], X_next[1], eps=0.001).round(4)}")
print(f"Градиент {np.sqrt((grad**2).sum()).round(9)}")

Значение функции 0.7723
x_min -0.3128
y_min -0.1569
Производная в x_min 0.0008
Производная в y_min -0.0002
Градиент 0.000963264
